services:
  db:
    image: postgres:16-alpine
    container_name: cuidou-db
    restart: always
    environment:
      POSTGRES_USER: cuidou_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cuidou_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
